# Generated by Django 5.1.7 on 2025-03-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_image_services_head_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='images1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='images10',
        ),
        migrations.RemoveField(
            model_name='services',
            name='images2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='images3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='images4',
        ),
        migrations.RemoveField(
            model_name='services',
            name='images5',
        ),
        migrations.RemoveField(
            model_name='services',
            name='images6',
        ),
        migrations.RemoveField(
            model_name='services',
            name='images7',
        ),
        migrations.RemoveField(
            model_name='services',
            name='images8',
        ),
        migrations.RemoveField(
            model_name='services',
            name='images9',
        ),
    ]
